### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/magufl-instagram-bootstrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @magufl  ,  ¡Felicidades! 
## Estilo de código y limpieza
- Código limpio y claro ¡Bien hecho! :heavy_check_mark:
## Mejores prácticas/comentarios
- Muy bien que no hayas tenido que utilizar un styles.css y que hayas podido hacerlo todo con las clases de bootstrap.
- ¡Me encantan las fotos que has elegido para el proyecto! :cat:

**Comment by magufl** [comment]
Gracias Edo!!

**Comment by EduardoHernandezGuzman** [comment]
A por el siguiente proyecto!!! :clap:
